version: '3'

services:
  haystack-api:
    image: "deepset/haystack:cpu-local"
    container_name: haystack-api
    volumes:
      - ./rest_api/rest_api/pipeline:/opt/pipelines
      - ./models:/opt/models
    ports:
      - 8000:8000
    restart: on-failure
    environment:
      # - DOCUMENTSTORE_PARAMS_HOST=elasticsearch
      - PIPELINE_YAML_PATH=/opt/pipelines/pipeline_mab_search.yml
      - QUERY_PIPELINE_NAMES=en_query
      - TOKENIZERS_PARALLELISM=false
    networks:
      - backend
    
networks:
  backend:
    external: true
