components:
  - name: EN_DocumentStore
    params:
      host: 172.21.5.208
      index: tri_test
      port: 30099
    type: ElasticsearchDocumentStore
  - name: EN_ESRetriever
    params:
      document_store: EN_DocumentStore
      passage_embedding_model: /home/c4i/trihm7/semantic_search/haystack/models/facebook/dpr-ctx_encoder-single-nq-base
      query_embedding_model: /home/c4i/trihm7/semantic_search/haystack/models/facebook/dpr-question_encoder-single-nq-base
      # passage_embedding_model: /opt/models/facebook/dpr-ctx_encoder-single-nq-base
      # query_embedding_model: /opt/models/facebook/dpr-question_encoder-single-nq-base
      use_gpu: false
    type: DensePassageRetriever
  - name: VI_DocumentStore
    params:
      host: 172.21.5.208
      index: tri_test
      port: 30099
    type: ElasticsearchDocumentStore
  - name: VI_ESRetriever
    params:
      document_store: VI_DocumentStore
      passage_embedding_model: /home/c4i/trihm7/semantic_search/haystack/models/facebook/dpr-ctx_encoder-single-nq-base
      query_embedding_model: /home/c4i/trihm7/semantic_search/haystack/models/facebook/dpr-question_encoder-single-nq-base
      use_gpu: false
    type: DensePassageRetriever
pipelines:
- name: en_query
  nodes:
    - inputs: [Query]
      name: EN_ESRetriever
# - name: vi_query
#   nodes:
#     - inputs: [Query]
#       name: VI_ESRetriever
version: 1.16.1
